---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
       organization: ${CF_ORGANIZATION}
       space: ${CF_SPACE}
       url: ${CF_TARGET_URL}
       application: ${CF_APP}
    script: |
     #!/bin/bash
     [ -f "bin/deployment/create_services.sh" ] && source bin/deployment/create_services.sh || echo "no create services script"
     cf push "${CF_APP}"
     # View logs
     #cf logs "${CF_APP}" --recent
